# Meta programming to allow for seemingly dynamic variable_map mappings

import pdxpy

generate_individual_if_setter = lambda k, n: {k: [{"limit": [f"$index$ = {n}"]}, {"set_global_variable": {"name": f"variable_map_$name$_index_{n}", "value": "$value$"}}]}

generate_individual_if_getter = lambda k, n: {
    k: [
        {"limit": [
            {"is_target_in_global_variable": 
                [ {"name": f"variable_map_$name$_index_{n}", "target": "$key$"} ]
            }
        ]},
        {
            "save_scope_value_as": {
                "name": "$save_as$",
                "value": "$key$"
            }
        }
        ]
    ]
}

with open("common/scripted_effects/variable_map_autogenerated.txt", "w") as f: 
    f.write(str(pdxpy.PdxObject(
        {
            "add_to_variable_map_dispatch": [
                generate_individual_if_setter("else_if" if n > 0 else "if", n) for n in range(101)
            ]
        }
    )))